exclude: |
  (?x)^(
    (.venv|venv)/|
    dist/|
    build/|
    node_modules/|
    \.mypy_cache/|
    \.ruff_cache/|
    status/
  )

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: []
        args:
          - --ignore-missing-imports
          - --pretty
          - --show-error-codes
          - --exclude
          - ^legacy/|

  - repo: local
    hooks:
      - id: pip-audit
        name: pip-audit (manual)
        entry: bash -lc 'pip install -q pip-audit && pip-audit'
        language: system
        pass_filenames: false
        stages: [manual]

ci:
  autofix_prs: false
  autoupdate_schedule: quarterly
