name: "v1.1 roadmap kickoff"
description: "Plan next iteration: strict typing expansion, telemetry, importers, CI gates"
title: "v1.1 roadmap kickoff"
labels: ["roadmap", "planning", "v1.1"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # 🚧 v1.1 roadmap kickoff
        Goal: Build on v1.0.0 GA by expanding strict typing, solidifying telemetry, and cleaning up importers — without breaking contracts.

  - type: checkboxes
    id: typing
    attributes:
      label: "🧩 Typing expansion"
      options:
        - label: "Re-enable strict pocket for `core.auth` (remove ignore and fix trivial annotations)"
        - label: "Re-enable strict pocket for `core.ui_blueprint` (stabilize DTO/view-models)"
        - label: "Gradually remove `ignore_errors` for `core.*_api` (one blueprint per PR)"
        - label: "Introduce `ParamSpec` / `Concatenate` for decorators to eliminate untyped-call noise"
        - label: "Promote `warn-return-any` globally once API handlers are clean"

  - type: checkboxes
    id: telemetry
    attributes:
      label: "📈 Telemetry & Observability"
      options:
        - label: "Decide on OTEL exporter (OTLP HTTP/gRPC) and configure minimal pipeline"
        - label: "Dashboards: p95 latency, 5xx rate, 429 rate, jwt_rejected_total, csrf_blocked_total"
        - label: "Alerts: thresholds for error rate & latency (warn/crit)"
        - label: "Expand domain metrics for import/export throughput and admin limits"

  - type: checkboxes
    id: importers
    attributes:
      label: "📦 Importers & Contracts"
      options:
        - label: "Consolidate importer modules under strict pocket (CSV, DOCX)"
        - label: "Deprecate legacy importer path; document replacements in README"
        - label: "Add OpenAPI examples for import payloads and errors"
        - label: "Strengthen 415/422 tests (mismatched content-type, invalid schema)"

  - type: checkboxes
    id: ci
    attributes:
      label: "🧪 CI & Developer Experience"
      options:
        - label: "Make pre-commit mandatory in CI (verify `pre-commit run -a`)"
        - label: "Quality workflow gates: Ruff, mypy, tests (fail fast on new violations)"
        - label: "Add a quickstart for strict pocket expansion (snippet + examples)"
        - label: "Optional: add coverage summary badge artifacts"

  - type: checkboxes
    id: delivery
    attributes:
      label: "🚀 Delivery"
      options:
        - label: "Milestone planning and triage labels ready"
        - label: "Draft v1.1 release notes template"
        - label: "Track contract changes via baseline diff (no breakage; additive only)"

  - type: textarea
    id: notes
    attributes:
      label: "Notes"
      description: "Owners, timelines, and links"
      placeholder: "Assign owners, set target dates, and link related PRs/issues"
    validations:
      required: false
