name: Lint & Type Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-type:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install ruff==0.6.3 mypy==1.11.2

      - name: Show tool versions
        run: |
          python --version
          ruff --version
          mypy --version
          python -m pip freeze | sed -n '1,120p'

      - name: Ruff Lint
        run: python -m ruff check .

      - name: Mypy Type Check
        run: python -m mypy --show-traceback --config-file mypy.ini .
