name: Quality
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

permissions:
  contents: read

jobs:
  lint-type-test:
    if: ${{ github.event.repository.private == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install quality deps
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ruff
        run: ruff check .

      - name: Mypy
        run: mypy

      - name: Pytest
        run: |
          pytest -q || ec=$?
          if [ "${ec:-0}" -eq 5 ]; then
            echo "No tests collected. Skipping as success."
            exit 0
          fi
          exit "${ec:-0}"
